export const ROLES = {
  USER: "user",
  MODERATOR: "moderator",
  ADMIN: "admin",
  USER_ADMIN: "user-admin",
  SUPER_ADMIN: "super-admin",
  AFFILIATE: "affiliate",
};

export const ROLE_GROUPS = {
  ALL_USERS: [
    ROLES.USER,
    ROLES.MODERATOR,
    ROLES.USER_ADMIN,
    ROLES.ADMIN,
    ROLES.SUPER_ADMIN,
    ROLES.AFFILIATE,
  ],

  MODS_AND_UP: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN],
  USER_ADMIN_AND_SUP: [ROLES.USER_ADMIN, ROLES.SUPER_ADMIN],
  ADMINS_AND_UP: [ROLES.ADMIN, ROLES.SUPER_ADMIN],

  SUPER_ADMIN_ONLY: [ROLES.SUPER_ADMIN],
};
