export const ADVANCED_PAYMENT_REQUEST = "ADVANCED_PAYMENT_REQUEST";
export const ADVANCED_PAYMENT_SUCCESS = "ADVANCED_PAYMENT_SUCCESS";
export const ADVANCED_PAYMENT_FAIL = "ADVANCED_PAYMENT_FAIL";

export const UPDATE_ADVANCED_PAYMENT_REQUEST =
  "UPDATE_ADVANCED_PAYMENT_REQUEST";
export const UPDATE_ADVANCED_PAYMENT_SUCCESS =
  "UPDATE_ADVANCED_PAYMENT_SUCCESS";
export const UPDATE_ADVANCED_PAYMENT_RESET = "UPDATE_ADVANCED_PAYMENT_RESET";
export const UPDATE_ADVANCED_PAYMENT_FAIL = "UPDATE_ADVANCED_PAYMENT_FAIL";

// Optional
export const DELETE_ADVANCED_PAYMENT_REQUEST =
  "DELETE_ADVANCED_PAYMENT_REQUEST";
export const DELETE_ADVANCED_PAYMENT_SUCCESS =
  "DELETE_ADVANCED_PAYMENT_SUCCESS";
export const DELETE_ADVANCED_PAYMENT_RESET = "DELETE_ADVANCED_PAYMENT_RESET";
export const DELETE_ADVANCED_PAYMENT_FAIL = "DELETE_ADVANCED_PAYMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
