// ✅ Get All Charges (Public & Admin)
export const ALL_CHARGE_REQUEST = "ALL_CHARGE_REQUEST";
export const ALL_CHARGE_SUCCESS = "ALL_CHARGE_SUCCESS";
export const ALL_CHARGE_FAIL = "ALL_CHARGE_FAIL";

export const ADMIN_CHARGE_REQUEST = "ADMIN_CHARGE_REQUEST";
export const ADMIN_CHARGE_SUCCESS = "ADMIN_CHARGE_SUCCESS";
export const ADMIN_CHARGE_FAIL = "ADMIN_CHARGE_FAIL";

// ✅ New Charge
export const NEW_CHARGE_REQUEST = "NEW_CHARGE_REQUEST";
export const NEW_CHARGE_SUCCESS = "NEW_CHARGE_SUCCESS";
export const NEW_CHARGE_FAIL = "NEW_CHARGE_FAIL";
export const NEW_CHARGE_RESET = "NEW_CHARGE_RESET";

// ✅ Update Charge
export const UPDATE_CHARGE_REQUEST = "UPDATE_CHARGE_REQUEST";
export const UPDATE_CHARGE_SUCCESS = "UPDATE_CHARGE_SUCCESS";
export const UPDATE_CHARGE_FAIL = "UPDATE_CHARGE_FAIL";
export const UPDATE_CHARGE_RESET = "UPDATE_CHARGE_RESET";

// ✅ Delete Charge
export const DELETE_CHARGE_REQUEST = "DELETE_CHARGE_REQUEST";
export const DELETE_CHARGE_SUCCESS = "DELETE_CHARGE_SUCCESS";
export const DELETE_CHARGE_FAIL = "DELETE_CHARGE_FAIL";
export const DELETE_CHARGE_RESET = "DELETE_CHARGE_RESET";

// ✅ Charge Details
export const CHARGE_DETAILS_REQUEST = "CHARGE_DETAILS_REQUEST";
export const CHARGE_DETAILS_SUCCESS = "CHARGE_DETAILS_SUCCESS";
export const CHARGE_DETAILS_FAIL = "CHARGE_DETAILS_FAIL";

// ✅ Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
