export const COIN_PURCHASE_VERIFY_REQUEST = "COIN_PURCHASE_VERIFY_REQUEST";
export const COIN_PURCHASE_VERIFY_SUCCESS = "COIN_PURCHASE_VERIFY_SUCCESS";
export const COIN_PURCHASE_VERIFY_FAIL = "COIN_PURCHASE_VERIFY_FAIL";

export const COIN_PURCHASE_FAIL_REQUEST = "COIN_PURCHASE_FAIL_REQUEST";
export const COIN_PURCHASE_FAIL_SUCCESS = "COIN_PURCHASE_FAIL_SUCCESS";
export const COIN_PURCHASE_FAIL_FAIL = "COIN_PURCHASE_FAIL_FAIL";

export const COIN_PURCHASE_CANCEL_REQUEST = "COIN_PURCHASE_CANCEL_REQUEST";
export const COIN_PURCHASE_CANCEL_SUCCESS = "COIN_PURCHASE_CANCEL_SUCCESS";
export const COIN_PURCHASE_CANCEL_FAIL = "COIN_PURCHASE_CANCEL_FAIL";
export const COIN_PURCHASE_INIT_REQUEST = "COIN_PURCHASE_INIT_REQUEST";
export const COIN_PURCHASE_INIT_SUCCESS = "COIN_PURCHASE_INIT_SUCCESS";
export const COIN_PURCHASE_INIT_FAIL = "COIN_PURCHASE_INIT_FAIL";
export const COIN_PURCHASE_CLEAR_ERRORS = "COIN_PURCHASE_CLEAR_ERRORS";
