// src/constants/logoChargeContants.js

// ✅ Get All Charges
export const ALL_LOGO_CHARGE_REQUEST = "ALL_LOGO_CHARGE_REQUEST";
export const ALL_LOGO_CHARGE_SUCCESS = "ALL_LOGO_CHARGE_SUCCESS";
export const ALL_LOGO_CHARGE_FAIL = "ALL_LOGO_CHARGE_FAIL";

// ✅ Get All Charges (Admin)
export const ADMIN_LOGO_CHARGE_REQUEST = "ADMIN_LOGO_CHARGE_REQUEST";
export const ADMIN_LOGO_CHARGE_SUCCESS = "ADMIN_LOGO_CHARGE_SUCCESS";
export const ADMIN_LOGO_CHARGE_FAIL = "ADMIN_LOGO_CHARGE_FAIL";

// ✅ Get Single Charge Details
export const LOGO_CHARGE_DETAILS_REQUEST = "LOGO_CHARGE_DETAILS_REQUEST";
export const LOGO_CHARGE_DETAILS_SUCCESS = "LOGO_CHARGE_DETAILS_SUCCESS";
export const LOGO_CHARGE_DETAILS_FAIL = "LOGO_CHARGE_DETAILS_FAIL";

// ✅ New Charge (Admin)
export const NEW_LOGO_CHARGE_REQUEST = "NEW_LOGO_CHARGE_REQUEST";
export const NEW_LOGO_CHARGE_SUCCESS = "NEW_LOGO_CHARGE_SUCCESS";
export const NEW_LOGO_CHARGE_FAIL = "NEW_LOGO_CHARGE_FAIL";
export const NEW_LOGO_CHARGE_RESET = "NEW_LOGO_CHARGE_RESET";

// ✅ Update Charge (Admin)
export const UPDATE_LOGO_CHARGE_REQUEST = "UPDATE_LOGO_CHARGE_REQUEST";
export const UPDATE_LOGO_CHARGE_SUCCESS = "UPDATE_LOGO_CHARGE_SUCCESS";
export const UPDATE_LOGO_CHARGE_FAIL = "UPDATE_LOGO_CHARGE_FAIL";
export const UPDATE_LOGO_CHARGE_RESET = "UPDATE_LOGO_CHARGE_RESET";

// ✅ Delete Charge (Admin)
export const DELETE_LOGO_CHARGE_REQUEST = "DELETE_LOGO_CHARGE_REQUEST";
export const DELETE_LOGO_CHARGE_SUCCESS = "DELETE_LOGO_CHARGE_SUCCESS";
export const DELETE_LOGO_CHARGE_FAIL = "DELETE_LOGO_CHARGE_FAIL";
export const DELETE_LOGO_CHARGE_RESET = "DELETE_LOGO_CHARGE_RESET";

// ✅ Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
