// dashboardConstants.jsx
export const DASHBOARD_STATS_REQUEST = "DASHBOARD_STATS_REQUEST";
export const DASHBOARD_STATS_SUCCESS = "DASHBOARD_STATS_SUCCESS";
export const DASHBOARD_STATS_FAIL = "DASHBOARD_STATS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
