// constants/genderConstants.js

// ✅ All Genders (Public)
export const ALL_GENDER_REQUEST = "ALL_GENDER_REQUEST";
export const ALL_GENDER_SUCCESS = "ALL_GENDER_SUCCESS";
export const ALL_GENDER_FAIL = "ALL_GENDER_FAIL";

// ✅ Admin Genders
export const ADMIN_GENDER_REQUEST = "ADMIN_GENDER_REQUEST";
export const ADMIN_GENDER_SUCCESS = "ADMIN_GENDER_SUCCESS";
export const ADMIN_GENDER_FAIL = "ADMIN_GENDER_FAIL";

// ✅ Gender Details
export const GENDER_DETAILS_REQUEST = "GENDER_DETAILS_REQUEST";
export const GENDER_DETAILS_SUCCESS = "GENDER_DETAILS_SUCCESS";
export const GENDER_DETAILS_FAIL = "GENDER_DETAILS_FAIL";

// ✅ Create Gender
export const NEW_GENDER_REQUEST = "NEW_GENDER_REQUEST";
export const NEW_GENDER_SUCCESS = "NEW_GENDER_SUCCESS";
export const NEW_GENDER_FAIL = "NEW_GENDER_FAIL";
export const NEW_GENDER_RESET = "NEW_GENDER_RESET";

// ✅ Update Gender
export const UPDATE_GENDER_REQUEST = "UPDATE_GENDER_REQUEST";
export const UPDATE_GENDER_SUCCESS = "UPDATE_GENDER_SUCCESS";
export const UPDATE_GENDER_FAIL = "UPDATE_GENDER_FAIL";
export const UPDATE_GENDER_RESET = "UPDATE_GENDER_RESET";

// ✅ Delete Gender
export const DELETE_GENDER_REQUEST = "DELETE_GENDER_REQUEST";
export const DELETE_GENDER_SUCCESS = "DELETE_GENDER_SUCCESS";
export const DELETE_GENDER_FAIL = "DELETE_GENDER_FAIL";
export const DELETE_GENDER_RESET = "DELETE_GENDER_RESET";

// ✅ Clear Errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
