export const ALL_LOGO_REQUEST = "ALL_LOGO_REQUEST";
export const ALL_LOGO_SUCCESS = "ALL_LOGO_SUCCESS";
export const ALL_LOGO_FAIL = "ALL_LOGO_FAIL";

export const ADMIN_LOGO_REQUEST = "ADMIN_LOGO_REQUEST";
export const ADMIN_LOGO_SUCCESS = "ADMIN_LOGO_SUCCESS";
export const ADMIN_LOGO_FAIL = "ADMIN_LOGO_FAIL";

export const NEW_LOGO_REQUEST = "NEW_LOGO_REQUEST";
export const NEW_LOGO_SUCCESS = "NEW_LOGO_SUCCESS";
export const NEW_LOGO_RESET = "NEW_LOGO_RESET";
export const NEW_LOGO_FAIL = "NEW_LOGO_FAIL";

export const UPDATE_LOGO_REQUEST = "UPDATE_LOGO_REQUEST";
export const UPDATE_LOGO_SUCCESS = "UPDATE_LOGO_SUCCESS";
export const UPDATE_LOGO_RESET = "UPDATE_LOGO_RESET";
export const UPDATE_LOGO_FAIL = "UPDATE_LOGO_FAIL";

export const DELETE_LOGO_REQUEST = "DELETE_LOGO_REQUEST";
export const DELETE_LOGO_SUCCESS = "DELETE_LOGO_SUCCESS";
export const DELETE_LOGO_RESET = "DELETE_LOGO_RESET";
export const DELETE_LOGO_FAIL = "DELETE_LOGO_FAIL";

export const LOGO_DETAILS_REQUEST = "LOGO_DETAILS_REQUEST";
export const LOGO_DETAILS_SUCCESS = "LOGO_DETAILS_SUCCESS";
export const LOGO_DETAILS_FAIL = "LOGO_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
