export const GET_NOTIFIES_REQUEST = "GET_NOTIFIES_REQUEST";
export const GET_NOTIFIES_SUCCESS = "GET_NOTIFIES_SUCCESS";
export const GET_NOTIFIES_FAIL = "GET_NOTIFIES_FAIL";
export const NEW_NOTIFICATION_RECEIVED = "NEW_NOTIFICATION_RECEIVED";

export const SEND_NOTIFICATION_REQUEST = "SEND_NOTIFICATION_REQUEST";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_FAIL = "SEND_NOTIFICATION_FAIL";
export const MARK_NOTIFICATION_READ_REQUEST = "MARK_NOTIFICATION_READ_REQUEST";
export const MARK_NOTIFICATION_READ_SUCCESS = "MARK_NOTIFICATION_READ_SUCCESS";
export const MARK_NOTIFICATION_READ_FAIL = "MARK_NOTIFICATION_READ_FAIL";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";

export const GET_NOTIFICATION_BY_ID_REQUEST = "GET_NOTIFICATION_BY_ID_REQUEST";
export const GET_NOTIFICATION_BY_ID_SUCCESS = "GET_NOTIFICATION_BY_ID_SUCCESS";
export const GET_NOTIFICATION_BY_ID_FAIL = "GET_NOTIFICATION_BY_ID_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
