export const NEW_NOTIFICATION_REQUEST = "NEW_NOTIFICATION_REQUEST";
export const NEW_NOTIFICATION_SUCCESS = "NEW_NOTIFICATION_SUCCESS";
export const NEW_NOTIFICATION_FAIL = "NEW_NOTIFICATION_FAIL";
export const NEW_NOTIFICATION_RESET = "NEW_NOTIFICATION_RESET";

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL";

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST";
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_FAIL = "UPDATE_NOTIFICATION_FAIL";
export const UPDATE_NOTIFICATION_RESET = "UPDATE_NOTIFICATION_RESET";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";
export const DELETE_NOTIFICATION_RESET = "DELETE_NOTIFICATION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
