export const PAYMENT_INITIALIZE_REQUEST = "PAYMENT_INITIALIZE_FAIL";
export const PAYMENT_INITIALIZE_SUCCESS = "PAYMENT_INITIALIZE_SUCCESS";
export const PAYMENT_INITIALIZE_FAIL = "PAYMENT_INITIALIZE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
