// Package Constants
export const CREATE_STRIPE_REQUEST = "CREATE_STRIPE_REQUEST";
export const CREATE_STRIPE_SUCCESS = "CREATE_STRIPE_SUCCESS";
export const CREATE_STRIPE_FAIL = "CREATE_STRIPE_FAIL";
export const CREATE_STRIPE_RESET = "CREATE_STRIPE_RESET";

export const CREATE_PAYPAL_REQUEST = "CREATE_PAYPAL_REQUEST";
export const CREATE_PAYPAL_SUCCESS = "CREATE_PAYPAL_SUCCESS";
export const CREATE_PAYPAL_FAIL = "CREATE_PAYPAL_FAIL";
export const CREATE_PAYPAL_RESET = "CREATE_PAYPAL_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
