export const ROLES = {
  USER: "user",
  MODERATOR: "moderator",
  ADMIN: "admin",
  SUPER_ADMIN: "super-admin",
};

export const ROLE_GROUPS = {
  ALL_USERS: [ROLES.USER, ROLES.MODERATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN],

  MODS_AND_UP: [ROLES.MODERATOR, ROLES.ADMIN, ROLES.SUPER_ADMIN],

  ADMINS_AND_UP: [ROLES.ADMIN, ROLES.SUPER_ADMIN],

  SUPER_ADMIN_ONLY: [ROLES.SUPER_ADMIN],
};
