export const ALL_SHIP_REQUEST = "ALL_SHIP_REQUEST";
export const ALL_SHIP_SUCCESS = "ALL_SHIP_SUCCESS";
export const ALL_SHIP_FAIL = "ALL_SHIP_FAIL";

export const ADMIN_SHIP_REQUEST = "ADMIN_SHIP_REQUEST";
export const ADMIN_SHIP_SUCCESS = "ADMIN_SHIP_SUCCESS";
export const ADMIN_SHIP_FAIL = "ADMIN_SHIP_FAIL";

export const NEW_SHIP_REQUEST = "NEW_SHIP_REQUEST";
export const NEW_SHIP_SUCCESS = "NEW_SHIP_SUCCESS";
export const NEW_SHIP_RESET = "NEW_SHIP_RESET";
export const NEW_SHIP_FAIL = "NEW_SHIP_FAIL";

export const UPDATE_SHIP_REQUEST = "UPDATE_SHIP_REQUEST";
export const UPDATE_SHIP_SUCCESS = "UPDATE_SHIP_SUCCESS";
export const UPDATE_SHIP_RESET = "UPDATE_SHIP_RESET";
export const UPDATE_SHIP_FAIL = "UPDATE_SHIP_FAIL";

export const DELETE_SHIP_REQUEST = "DELETE_SHIP_REQUEST";
export const DELETE_SHIP_SUCCESS = "DELETE_SHIP_SUCCESS";
export const DELETE_SHIP_RESET = "DELETE_SHIP_RESET";
export const DELETE_SHIP_FAIL = "DELETE_SHIP_FAIL";

export const SHIP_DETAILS_REQUEST = "SHIP_DETAILS_REQUEST";
export const SHIP_DETAILS_SUCCESS = "SHIP_DETAILS_SUCCESS";
export const SHIP_DETAILS_FAIL = "SHIP_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
