// constants/subcategoryConstants.js

export const ALL_SUBCATEGORY_REQUEST = "ALL_SUBCATEGORY_REQUEST";
export const ALL_SUBCATEGORY_SUCCESS = "ALL_SUBCATEGORY_SUCCESS";
export const ALL_SUBCATEGORY_FAIL = "ALL_SUBCATEGORY_FAIL";

export const ADMIN_SUBCATEGORY_REQUEST = "ADMIN_SUBCATEGORY_REQUEST";
export const ADMIN_SUBCATEGORY_SUCCESS = "ADMIN_SUBCATEGORY_SUCCESS";
export const ADMIN_SUBCATEGORY_FAIL = "ADMIN_SUBCATEGORY_FAIL";

export const NEW_SUBCATEGORY_REQUEST = "NEW_SUBCATEGORY_REQUEST";
export const NEW_SUBCATEGORY_SUCCESS = "NEW_SUBCATEGORY_SUCCESS";
export const NEW_SUBCATEGORY_RESET = "NEW_SUBCATEGORY_RESET";
export const NEW_SUBCATEGORY_FAIL = "NEW_SUBCATEGORY_FAIL";

export const UPDATE_SUBCATEGORY_REQUEST = "UPDATE_SUBCATEGORY_REQUEST";
export const UPDATE_SUBCATEGORY_SUCCESS = "UPDATE_SUBCATEGORY_SUCCESS";
export const UPDATE_SUBCATEGORY_RESET = "UPDATE_SUBCATEGORY_RESET";
export const UPDATE_SUBCATEGORY_FAIL = "UPDATE_SUBCATEGORY_FAIL";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_RESET = "DELETE_SUBCATEGORY_RESET";
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL";

export const SUBCATEGORY_DETAILS_REQUEST = "SUBCATEGORY_DETAILS_REQUEST";
export const SUBCATEGORY_DETAILS_SUCCESS = "SUBCATEGORY_DETAILS_SUCCESS";
export const SUBCATEGORY_DETAILS_FAIL = "SUBCATEGORY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
