// constants/subsubcategoryConstants.js

export const ALL_SUBSUBCATEGORY_REQUEST = "ALL_SUBSUBCATEGORY_REQUEST";
export const ALL_SUBSUBCATEGORY_SUCCESS = "ALL_SUBSUBCATEGORY_SUCCESS";
export const ALL_SUBSUBCATEGORY_FAIL = "ALL_SUBSUBCATEGORY_FAIL";

export const ADMIN_SUBSUBCATEGORY_REQUEST = "ADMIN_SUBSUBCATEGORY_REQUEST";
export const ADMIN_SUBSUBCATEGORY_SUCCESS = "ADMIN_SUBSUBCATEGORY_SUCCESS";
export const ADMIN_SUBSUBCATEGORY_FAIL = "ADMIN_SUBSUBCATEGORY_FAIL";

export const NEW_SUBSUBCATEGORY_REQUEST = "NEW_SUBSUBCATEGORY_REQUEST";
export const NEW_SUBSUBCATEGORY_SUCCESS = "NEW_SUBSUBCATEGORY_SUCCESS";
export const NEW_SUBSUBCATEGORY_RESET = "NEW_SUBSUBCATEGORY_RESET";
export const NEW_SUBSUBCATEGORY_FAIL = "NEW_SUBSUBCATEGORY_FAIL";

export const UPDATE_SUBSUBCATEGORY_REQUEST = "UPDATE_SUBSUBCATEGORY_REQUEST";
export const UPDATE_SUBSUBCATEGORY_SUCCESS = "UPDATE_SUBSUBCATEGORY_SUCCESS";
export const UPDATE_SUBSUBCATEGORY_RESET = "UPDATE_SUBSUBCATEGORY_RESET";
export const UPDATE_SUBSUBCATEGORY_FAIL = "UPDATE_SUBSUBCATEGORY_FAIL";

export const DELETE_SUBSUBCATEGORY_REQUEST = "DELETE_SUBSUBCATEGORY_REQUEST";
export const DELETE_SUBSUBCATEGORY_SUCCESS = "DELETE_SUBSUBCATEGORY_SUCCESS";
export const DELETE_SUBSUBCATEGORY_RESET = "DELETE_SUBSUBCATEGORY_RESET";
export const DELETE_SUBSUBCATEGORY_FAIL = "DELETE_SUBSUBCATEGORY_FAIL";

export const SUBSUBCATEGORY_DETAILS_REQUEST = "SUBSUBCATEGORY_DETAILS_REQUEST";
export const SUBSUBCATEGORY_DETAILS_SUCCESS = "SUBSUBCATEGORY_DETAILS_SUCCESS";
export const SUBSUBCATEGORY_DETAILS_FAIL = "SUBSUBCATEGORY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
